# Generated by Django 4.0.6 on 2023-07-04 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instant', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Follows2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='person2', to=settings.AUTH_USER_MODEL)),
                ('userers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to=settings.AUTH_USER_MODEL)),
            ],
        ),]


